# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=128)),
                ('cover', models.IntegerField(default=0)),
                ('parent', models.IntegerField(default=0)),
                ('update_at', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
